#!/usr/bin/env python3

import argparse
import getpass
import hashlib
import sys
import urllib.request

parser = argparse.ArgumentParser(description='Check securely whether the password is listed on haveibeenpwned.com')
parser.add_argument('-p', '--password',
                    help='the password to check. Overrides <password_file>')
parser.add_argument('-s', '--secret', action='store_true', default=False,
                    help='conceal the password when interactively reading from stdin')
parser.add_argument('password_file', 
                    nargs='?', type=argparse.FileType('r'),
                    default=sys.stdin,
                    help='read the password from this file; stdin by default')
args = parser.parse_args()

if args.password:
    password = args.password.encode()
else:
    if args.secret:
        password = getpass.getpass().encode()
    else:
        password = args.password_file.read().encode()

hash = hashlib.sha1(password).hexdigest().upper()
prefix, suffix = hash[:5], hash[5:]

request = urllib.request.Request(
    url='https://api.pwnedpasswords.com/range/' + prefix,
    headers={'User-Agent': 'is-password-compromised'}
)

candidates = urllib.request.urlopen(request).read()

occurrence = '0'
for candidate in candidates.decode().splitlines():
    candidate_suffix, candidate_occurrence = candidate.split(':')
    if candidate_suffix == suffix:
        occurrence = candidate_occurrence

if args.secret:
    print('You password was hacked {} times'.format(occurrence))
else:
    print(occurrence)

