#!/usr/bin/env python3

import argparse
import hashlib
import sys
import urllib.request

parser = argparse.ArgumentParser(description="Check securely whether the password is listed on haveibeenpwned.com")
parser.add_argument("password", help="the password to check")
args = parser.parse_args()

hash = hashlib.sha1(args.password.encode()).hexdigest().upper()
prefix, suffix = hash[:5], hash[5:]

request = urllib.request.Request(
    url='https://api.pwnedpasswords.com/range/' + prefix,
    headers={'User-Agent': 'is-password-compromised'}
)

candidates = urllib.request.urlopen(request).read()

for candidate in candidates.decode().splitlines():
    candidate_suffix, occurrence = candidate.split(':')
    if candidate_suffix == suffix:
        print(occurrence)
        sys.exit(0)

print('0')
sys.exit(0)
